# Generated by Django 4.0.6 on 2022-07-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.FloatField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('material', models.CharField(max_length=30)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(upload_to='uploads/')),
            ],
            options={
                'unique_together': {('product_name', 'size', 'material')},
            },
        ),
    ]
